import dateFormat from 'dateformat';

export const dateFormatBR = (date, options) => {
  dateFormat.i18n = {
    dayNames: [
      'Sun',
      'Mon',
      'Tue',
      'Wed',
      'Thurs',
      'Fri',
      'Sat',
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    monthNames: [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sept',
      'Ouct',
      'Nov',
      'Dec',
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    timeNames: ['a', 'p', 'am', 'pm', 'A', 'P', 'AM', 'PM'],
  };

  return dateFormat(date, 'dddd, d mmmm, yyyy "at" HH:MM:ss');
};



// dateFormat.i18n = {
//   dayNames: [
//     'Dom',
//     'Seg',
//     'Ter',
//     'Qua',
//     'Qui',
//     'Sex',
//     'Sab',
//     'Domingo',
//     'Segunda',
//     'Terca',
//     'Quarta',
//     'Quinta',
//     'Sexta',
//     'Sabado',
//   ],
//   monthNames: [
//     'Jan',
//     'Fev',
//     'Mar',
//     'Abr',
//     'Maio',
//     'Jun',
//     'Jul',
//     'Ago',
//     'Set',
//     'Out',
//     'Nov',
//     'Dez',
//     'Janeiro',
//     'Fevereiro',
//     'Marco',
//     'Abril',
//     'Maio',
//     'Junho',
//     'Julho',
//     'Agosto',
//     'Setembro',
//     'Outubro',
//     'Novembro',
//     'Dezembro',
//   ],
//   timeNames: ['a', 'p', 'am', 'pm', 'A', 'P', 'AM', 'PM'],
// };
